using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;

namespace GtMotive.Estimate.Microservice.Api.OutputPorts
{
    /// <summary>
    /// Standard output port implementation used by the HTTP presentation layer.
    /// </summary>
    /// <typeparam name="TUseCaseOutput">
    /// Type of the output generated by the use case.
    /// </typeparam>
    public sealed class OutputPort<TUseCaseOutput>
        : IOutputPortStandard<TUseCaseOutput>
        where TUseCaseOutput : IUseCaseOutput
    {
        /// <summary>
        /// Gets the response generated by the use case.
        /// </summary>
        public TUseCaseOutput Response { get; private set; }

        /// <summary>
        /// Handles the output generated by the use case.
        /// </summary>
        /// <param name="response">
        /// Response generated by the use case.
        /// </param>
        public void StandardHandle(TUseCaseOutput response)
        {
            Response = response;
        }
    }
}
