using System;
using GtMotive.Estimate.Microservice.Api.Models;
using GtMotive.Estimate.Microservice.Api.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GtMotive.Estimate.Microservice.Api.Presenters
{
    /// <summary>
    /// Presents the result of the create vehicle use case
    /// as an HTTP API response.
    /// </summary>
    public sealed class CreateVehiclePresenter
        : IOutputPortStandard<CreateVehicleOutput>, IWebApiPresenter
    {
        /// <summary>
        /// Gets the output generated by the use case.
        /// </summary>
        public CreateVehicleOutput Response { get; private set; }

        /// <summary>
        /// Gets the HTTP action result generated by the presenter.
        /// </summary>
        public IActionResult ActionResult { get; private set; }

        /// <summary>
        /// Handles the output generated by the create vehicle use case.
        /// </summary>
        /// <param name="response">
        /// Output generated by the create vehicle use case.
        /// </param>
        public void StandardHandle(CreateVehicleOutput response)
        {
            ArgumentNullException.ThrowIfNull(response);

            Response = response;

            var apiResponse = new CreateVehicleResponse(
                response.VehicleId,
                response.RegistrationNumber);
            ActionResult = new CreatedResult($"/vehicles/{response.VehicleId}", apiResponse);
        }
    }
}
