using System;
using System.Linq;
using GtMotive.Estimate.Microservice.Api.Models;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;

namespace GtMotive.Estimate.Microservice.Api.Presenters
{
    /// <summary>
    /// Presents the result of the list vehicles use case
    /// as an HTTP API response.
    /// </summary>
    public sealed class ListVehiclesPresenter
        : IOutputPortStandard<ListVehiclesOutput>
    {
        /// <summary>
        /// Gets the output generated by the use case.
        /// </summary>
        public ListVehiclesOutput Response { get; private set; }

        /// <summary>
        /// Gets the HTTP response generated by the presenter.
        /// </summary>
        public ListVehiclesResponse ApiResponse { get; private set; }

        /// <summary>
        /// Handles the output generated by the list vehicles use case.
        /// </summary>
        /// <param name="response">
        /// Output generated by the list vehicles use case.
        /// </param>
        public void StandardHandle(ListVehiclesOutput response)
        {
            ArgumentNullException.ThrowIfNull(response);

            Response = response;

            ApiResponse = new ListVehiclesResponse(
                [.. response.Vehicles
                    .Select(vehicle => new VehicleResponse(
                        vehicle.Id,
                        vehicle.RegistrationNumber,
                        vehicle.ManufacturingDate,
                        vehicle.Status))]);
        }
    }
}
