using System;
using System.Linq;
using GtMotive.Estimate.Microservice.Api.Models;
using GtMotive.Estimate.Microservice.Api.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GtMotive.Estimate.Microservice.Api.Presenters
{
    /// <summary>
    /// Presents the result of the list vehicles use case
    /// as an HTTP API response.
    /// </summary>
    public sealed class ListVehiclesPresenter
        : IOutputPortStandard<ListVehiclesOutput>, IWebApiPresenter
    {
        /// <summary>
        /// Gets the output generated by the use case.
        /// </summary>
        public ListVehiclesOutput Response { get; }

        /// <summary>
        /// Gets the HTTP action result generated by the presenter.
        /// </summary>
        public IActionResult ActionResult { get; private set; }

        /// <summary>
        /// Handles the output generated by the list vehicles use case.
        /// </summary>
        /// <param name="response">
        /// Output generated by the list vehicles use case.
        /// </param>
        public void StandardHandle(ListVehiclesOutput response)
        {
            ArgumentNullException.ThrowIfNull(response);

            var vehicles = response.Vehicles
                .Select(vehicle => new VehicleResponse(
                    vehicle.Id,
                    vehicle.RegistrationNumber,
                    vehicle.ManufacturingDate,
                    vehicle.Status))
                .ToList();

            ActionResult = new OkObjectResult(
                new ListVehiclesResponse(vehicles));
        }
    }
}
