using System;
using GtMotive.Estimate.Microservice.Api.Models;
using GtMotive.Estimate.Microservice.Api.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GtMotive.Estimate.Microservice.Api.Presenters
{
    /// <summary>
    /// Presents the result of the rent vehicle use case
    /// as an HTTP API response.
    /// </summary>
    public sealed class RentVehiclePresenter
        : IOutputPortStandard<RentVehicleOutput>, IWebApiPresenter
    {
        /// <summary>
        /// Gets the output generated by the use case.
        /// </summary>
        public RentVehicleOutput Response { get; private set; }

        /// <summary>
        /// Gets the HTTP action result generated by the presenter.
        /// </summary>
        public IActionResult ActionResult { get; private set; }

        /// <summary>
        /// Handles the output generated by the rent vehicle use case.
        /// </summary>
        /// <param name="response">
        /// Output generated by the rent vehicle use case.
        /// </param>
        public void StandardHandle(RentVehicleOutput response)
        {
            ArgumentNullException.ThrowIfNull(response);

            Response = response;

            var apiResponse = new RentVehicleResponse(
                response.RentalId,
                response.VehicleId,
                response.CustomerId);

            ActionResult = new CreatedResult(
                $"/rentals/{response.RentalId}",
                apiResponse);
        }
    }
}
