using System;
using GtMotive.Estimate.Microservice.Api.Models;
using GtMotive.Estimate.Microservice.Api.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases;
using GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GtMotive.Estimate.Microservice.Api.Presenters
{
    /// <summary>
    /// Presents the result of the return vehicle use case
    /// as an HTTP API response.
    /// </summary>
    public sealed class ReturnVehiclePresenter
        : IOutputPortStandard<ReturnVehicleOutput>, IWebApiPresenter
    {
        /// <summary>
        /// Gets the output generated by the use case.
        /// </summary>
        public ReturnVehicleOutput Response { get; private set; }

        /// <summary>
        /// Gets the HTTP action result generated by the presenter.
        /// </summary>
        public IActionResult ActionResult { get; private set; }

        /// <summary>
        /// Handles the output generated by the return vehicle use case.
        /// </summary>
        /// <param name="response">
        /// Output generated by the return vehicle use case.
        /// </param>
        public void StandardHandle(ReturnVehicleOutput response)
        {
            ArgumentNullException.ThrowIfNull(response);

            Response = response;

            // Ajusta 'ReturnVehicleResponse' al nombre de tu DTO/Modelo de respuesta HTTP si difiere
            var apiResponse = new ReturnVehicleResponse(
                response.VehicleId,
                response.ReturnedAt);

            ActionResult = new OkObjectResult(apiResponse);
        }
    }
}
